// generated by Fast Light User Interface Designer (fluid) version 2.0100

#ifndef Test3_h
#define Test3_h
// Header for This example is completely written using fluid2.
#include <fltk/Window.h>
#include <fltk/RegionHolder.h>
extern fltk::RegionHolder* region;
#include <fltk/BarHolder.h>
#include <fltk/ToolBar.h>
#include <fltk/HighlightButton.h>
#include <fltk/ToolDivider.h>
#include <fltk/InputBrowser.h>
extern fltk::InputBrowser* inb;
#include <fltk/DockHolder.h>
#include <fltk/TextEditor.h>
#endif
